<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SK33D9P" failures="1" tests="2" name="runner.TestRunner" time="18.847" errors="0" timestamp="2025-09-07T18:44:55 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="12.665">
    <failure message="OTP verification failed: Incorrect OTP, 2 attempts left" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: OTP verification failed: Incorrect OTP, 2 attempts left
at pages.LoginPage.validateOtpResult(LoginPage.java:78)
at stepdefinitions.Login.the_user_enters_the_otp(Login.java:39)
at âœ½.the user enters the otp(file:///D:/CapgeminiTesting/Apollo_247_testing_app/src/test/resources/features/login.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="6.182"/>
</testsuite> <!-- runner.TestRunner -->
